config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root "trumps#index"
 resources :trumps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trump.rb
class Trump < ApplicationRecord
   belongs_to :user
   validates :title, length: {minimum: 3}
   validates :body, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trumps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trumps_controller.rb
class TrumpsController < ApplicationController
before_action :find_post, only: [:show, :edit, :destroy, :update]
before_action :authenticate_user!, only: [:new, :edit, :destroy]
before_action :is_owner, only: [:edit, :destroy]
   def index
     @trumps = Trump.all.order("created_at DESC")
   end

   def show
   end

   def new
     @trump = Trump.new
   end

   def create
    @trump = current_user.trumps.build(post_params)
    if @trump.save
      redirect_to @trump, notice: "Post was successfully created!"
    else
      render "new"
    end
  end

 def edit
  end


 def update
    if @trump.update(post_params)
     redirect_to @trump
   else
     render "edit"
   end
 end


 def destroy
   @trump.destroy
   redirect_to  root_path
  end

   private


def find_post
  @trump = Trump.find(params[:id])
end

   def post_params
     params.require(:trump).permit(:title, :body, :user_id)
   end

   def is_owner
   unless current_user == @trump.user
     flash[:alert] = "That post doesn't belong to you!"
     redirect_to @trump
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trumps_helper.rb
module TrumpsHelper
end

app/views/layouts/application.html.haml
!!! 5
%head
%title Trumpler
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
 %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  .navbar-brand= link_to "Trumps Dumps", root_path
  %ul.nav.navbar-nav.navbar-right
   %li= link_to "New Dump", new_trump_path
   %li= link_to "Sign Out", destroy_user_session_path, method: :delete
   %li= link_to "Sign In", user_session_path

- if notice
 = notice
- if alert
 = alert
.container
 = yield

app/views/trumps/_form.html.haml
.form
 = simple_form_for(@trump, html: { class: 'form-horizontal' }) do |f|
  = f.input :title
  = f.input :body
  = f.button :submit

app/views/trumps/edit.html.haml
%h1 Edit  a post:
=  render "form"
%small= link_to "Cancel", trump_path(@trump)

app/views/trumps/index.html.haml
%h1 Here are all your dumps:
- @trumps.each do |trump|
 .trump
  %h1= link_to trump.title, trump
  %small
   Created by:
   = trump.user.email

app/views/trumps/new.html.haml
%h1 create  a post:
= render "form"
%small= link_to "Cancel", root_path

app/views/trumps/show.html.haml
.content
 %small= @trump.user.email
 %h1=  @trump.title
 %p=  @trump.body
 %br
 %small= link_to "Back", root_path

 - if current_user == @trump.user
  %small= link_to "Edit", edit_trump_path
  %small= link_to "Delete", @trump, method: :delete, data: {confirm: "Are you sure?"}